### PR TITLE
Fixes potential DMARC issue, availability zone rebalancing, optimizations for cost and adds IPV6 support and serverless analytics environment

### PR DESCRIPTION
**Pull request by Jmevorach**
Implements scale to zero for RDS and also makes it so that email receiving is always turned on if SES is configured at help@$your_domain so that DMARC always has a valid email address associated with your domain to send emails to.

### CODE REVIEW

**Comment by Jmevorach** [comment]
Also added support for IPV6 and availability zone rebalancing.

**Comment by Jmevorach** [comment]
Added a serverless analytics environment that can be toggled on/off with a parameter in cdk.json.

**Comment by Jmevorach** [comment]
Going to add more documentation and a few other things.

**Comment by Jmevorach** [comment]
Done! Everything's tested and documented!

**Comment by jesdynf** [comment]
Am interested in seeing if the Jupyter work gets any nibbles. Thanks!

**Comment by adunsulag** [comment]
@Jmevorach Got a chance finally to look this over.  Very fascinating and neat stuff there.  One question that came up for me here is from an audit perspective when the data is extracted for the analytics or for AWS Bedrock, that we make sure something gets clearly logged that a data extraction event took place.  Perhaps that could end up going to CloudTrail (or perhaps CloudWatch) that the extraction took place and the user that initiated the extraction.  

I thought about maybe having some kind of Audit api endpoint and just logging it at the application layer which makes it easy if the patient requests an audit log under HIPAA of who saw their data, but its probably too much work as we'd likely need some kind of lambda triggered to hit the API endpoint to log the behavior.  From an audit perspective, we'd just want to make sure we have a record of when PHI has been extracted, who did that, and where the data was sent.

**Comment by Jmevorach** [comment]
Thanks @jesdynf and @adunsulag really appreciate it! 

In terms of the data extraction piece both for Sagemaker Studio and Bedrock no PHI or anything like that should leave the VPC/account and both have been configured to use private VPC endpoints. If you choose to fine tune a model for instance that will be done on a private copy of the model that's isolated to your account (docs [here](https://aws.amazon.com/bedrock/security-compliance/#:~:text=Amazon%20Bedrock%20helps%20ensure%20that,in%20compliance%20with%20the%20GDPR.)). For Sagemaker Studio we use the VPC only mode (docs [here](https://docs.aws.amazon.com/sagemaker/latest/dg/studio-notebooks-and-internet-access.html#:~:text=Requirements%20to%20use%20VPC%20only%20mode)).  

Things within Sagemaker and Bedrock should be getting logged already to both Cloudtrail and Cloudwatch. By default Cloudtrail should retain logs for 90 days. If there's a certain period of time we'd like to make sure we retain records for I can look into how we can accomplish that.

**Comment by Jmevorach** [comment]
@adunsulag Got you! No problem; I'll look into it!

**Comment by Jmevorach** [comment]
@adunsulag ; we should be good to go with https://github.com/openemr/host-openemr-on-aws-fargate/pull/31

**Pull request merged**
